package com.green.dao.output;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.green.dao.output.MyBook;
import com.green.dao.output.Dict;

import com.green.dao.output.MyBookDao;
import com.green.dao.output.DictDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myBookDaoConfig;
    private final DaoConfig dictDaoConfig;

    private final MyBookDao myBookDao;
    private final DictDao dictDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myBookDaoConfig = daoConfigMap.get(MyBookDao.class).clone();
        myBookDaoConfig.initIdentityScope(type);

        dictDaoConfig = daoConfigMap.get(DictDao.class).clone();
        dictDaoConfig.initIdentityScope(type);

        myBookDao = new MyBookDao(myBookDaoConfig, this);
        dictDao = new DictDao(dictDaoConfig, this);

        registerDao(MyBook.class, myBookDao);
        registerDao(Dict.class, dictDao);
    }
    
    public void clear() {
        myBookDaoConfig.clearIdentityScope();
        dictDaoConfig.clearIdentityScope();
    }

    public MyBookDao getMyBookDao() {
        return myBookDao;
    }

    public DictDao getDictDao() {
        return dictDao;
    }

}
