package com.green.dao.output;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DICT".
 */
@Entity
public class Dict {

    @Id
    @Index
    private Long id;
    private String title;
    private String version;
    private String category;
    private String type;
    private String entry_cout;
    private String file_size;
    private String content;
    private Byte status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Dict() {
    }

    public Dict(Long id) {
        this.id = id;
    }

    @Generated
    public Dict(Long id, String title, String version, String category, String type, String entry_cout, String file_size, String content, Byte status) {
        this.id = id;
        this.title = title;
        this.version = version;
        this.category = category;
        this.type = type;
        this.entry_cout = entry_cout;
        this.file_size = file_size;
        this.content = content;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getEntry_cout() {
        return entry_cout;
    }

    public void setEntry_cout(String entry_cout) {
        this.entry_cout = entry_cout;
    }

    public String getFile_size() {
        return file_size;
    }

    public void setFile_size(String file_size) {
        this.file_size = file_size;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
